services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - cloud-mongo:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rq-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python worker.py
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env
    volumes:
      - ./backend:/app

  rq-scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python scheduler.py
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env
    volumes:
      - ./backend:/app

volumes:
  cloud-mongo: