FROM python:3.11-slim

WORKDIR /app


# Install Poppler and Python dependencies
RUN apt-get update && \
    apt-get install -y poppler-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000


CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --reload --port 8000 --reload-dir /app "]
